Web/Models/Product.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.InteropServices;
using System.Xml.Linq;

namespace Web.Models
{
    [Table ("Products")]
    public class Product
    {
        [Key]
        public int id { get; set; }
        [Required]
        public string name { get; set; }
        public string desc { get; set; }
        public string SKU { get; set; }
        [Required]
        public decimal price { get; set; }
        [Required]
        public int category_id { get; set; }

    }
}

Web/Controllers/ImageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Web.Models;

namespace Web.Controllers
{
    [Secured]
    public class ImageController : Controller
    {
        MyContext _context=new MyContext();
        private readonly IWebHostEnvironment _hostEnvironment;

        public ImageController(MyContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            List<Product> products=_context.Products.ToList();
            List<Image> images = _context.Images.ToList();
            this.ViewBag.Products = products;
            return View(images);
        }

        
        public IActionResult Delete(int? id,int? productID)
        {
            //this.ViewBag.productID = this.TempData["backtosite"];
            if (id==null)
            {
                return NotFound();
            }
            Image selected = _context.Images.Find(id);
            //_context.Images.Remove(deleted);
            //return View("Upsert", "Product", ViewBag.BackToSite);
            this.ViewBag.ProductID = productID;
            return View(selected);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteImage(int id,int? productID)
        {
            string wwwRootPath = _hostEnvironment.WebRootPath;
            
            Image deleted= _context.Images.Find(id);
            string delete = wwwRootPath + deleted.path;
            System.IO.File.Delete(delete);
            _context.Images.Remove(deleted);
            _context.SaveChanges();
            //return RedirectToAction("Upsert", "Product", this.ViewBag.site);
            return RedirectToAction("Upsert", "Product", new { id = productID } );
        }
    }
}

Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System.Runtime.CompilerServices;
using Ubiety.Dns.Core.Records.NotUsed;
using Web.Models;
using Web.Utils;

namespace Web.Controllers
{
    //[Secured]
    public class ProductController : BaseController
    {
        private MyContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        public ProductController(MyContext context, IWebHostEnvironment hostEnvironment)
        {
            this._context = context;
            _hostEnvironment = hostEnvironment;
        }
        // GET: ProductController
        public ActionResult Index()
        {
            List<Product> ProductList = _context.Products.ToList();            
            this.ViewBag.Images = _context.Images.ToList();
            return View(ProductList);
        }


        //GET
        public ActionResult Upsert(int? id)
        {
            Product product = new Product();
            if (id == null || id == 0)
            {
                return View(product);
            }
            else
            {
                Product selected = _context.Products.Find(id);
                List<Image> Images = _context.Images.ToList();
                List<Image> AdditionalImages=new List<Image>();
                foreach (var item in Images)
                {
                    if (item.product_id==selected.id && item.priority==2)
                    {
                        AdditionalImages.Add(item);
                    }
                }
                return View(selected);
            }
        }
        // POST: ProductController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Upsert(Product obj,IFormFile? file)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        //startImage
        //        string wwwRootPath = _hostEnvironment.WebRootPath;
        //        if (file != null)
        //        {
        //            string fileName = Guid.NewGuid().ToString();
        //            var uploads = Path.Combine(wwwRootPath, @"images\products");
        //            var extension = Path.GetExtension(file.FileName);

        //            if (obj.photoMain != null)
        //            {
        //                var oldImagePath = Path.Combine(wwwRootPath, obj.photoMain.TrimStart('\\'));
        //                if (System.IO.File.Exists(oldImagePath))
        //                {
        //                    System.IO.File.Delete(oldImagePath);
        //                }
        //            }

        //            using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
        //            {
        //                file.CopyTo(fileStreams);
        //            }
        //            obj.photoMain = @"\images\products\" + fileName + extension;

        //        }
        //        //endImage
        //        if (obj.id == 0)
        //        {
        //            _context.Products.Add(obj);
        //        }
        //        else
        //        {
        //            _context.Products.Update(obj);
        //        }
                
        //        _context.SaveChanges();
        //        TempData["success"] = "Product created successfully";
        //        return RedirectToAction("Index");
        //    }
        //    return View(obj);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upsert(Product obj, IList<IFormFile>? listImages,IFormFile? mainPhoto)
        {
            if (ModelState.IsValid)
            {
                if (obj.id == 0)
                {
                    _context.Products.Add(obj);
                }
                else
                {
                    _context.Products.Update(obj);
                }
                _context.SaveChanges();
                //startImage
                //string wwwRootPath = _hostEnvironment.WebRootPath;
                using (ImageService service = new ImageService(_context, _hostEnvironment))
                {
                        service.Upload(obj, listImages);

                    
                        service.Upload(obj, mainPhoto,1);
                    
                };
                

                


                //endImage                    
                TempData["success"] = "Product created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Product selected = _context.Products.Find(id);
            if (selected == null)
            {
                return NotFound();
            }
            return View(selected);
        }

        // POST: ProductController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteProduct(int? id)
        {
            List<TotalProduct> variants = _context.Variants.ToList();
            List<Image> images=_context.Images.ToList();
            Product selected = _context.Products.Find(id);
            string wwwRootPath = _hostEnvironment.WebRootPath;
            foreach (Image item in images)
            {
                if (item.product_id==selected.id)
                {
                    string uploads = wwwRootPath + item.path;////////dodělat

                    System.IO.File.Delete(uploads);
                    _context.Images.Remove(item);
                    _context.SaveChanges();
                }
                
                if (selected == null)
                {
                    return NotFound();
                }
            }
            
            foreach (var item in variants)
            {
                if (item.product.id == id)
                {
                    _context.Variants.Remove(item);
                }
            }
            
            _context.SaveChanges();
            _context.Products.Remove(selected);
            _context.SaveChanges();
            TempData["success"] = "Product deleted successfully";
            return RedirectToAction("Index");
        }

        //GET
        public IActionResult Variant(int? id)
        {
            Product selected = _context.Products.Find(id);
            return View(selected);
        }
        public IActionResult DelVariant(int? id)
        {
            TotalProduct selected = _context.Variants.Find(id);
            List<Product> products = _context.Products.ToList();
            List<Size> sizes = _context.Sizes.ToList();
            List<Color> colors = _context.Colors.ToList();
            this.ViewBag.Products = products;
            this.ViewBag.Sizes = sizes;
            this.ViewBag.Colors = colors;
            return View(selected);
        }
        [HttpPost, ActionName("DelVariant")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteVariant(int? id)
        {
            TotalProduct selected = _context.Variants.Find(id);
            _context.Variants.Remove(selected);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        //GET
        public IActionResult CreateVariant(int id)
        {
            Product selected = _context.Products.Find(id);
            TotalProduct selectedProduct = new TotalProduct();
            selectedProduct.product =selected;

            this.ViewBag.Colors = _context.Colors.ToList();
            this.ViewBag.Sizes = _context.Sizes.ToList();

            return View(selectedProduct);
        }

        [HttpPost, ActionName("CreateVariant")]
        public IActionResult CreateVariant(TotalProduct variant,int? productId)
        {
            
                Product product = _context.Products.Find(productId);
                variant.product = product;
                variant.id = 0;
                _context.Variants.Add(variant);
                _context.SaveChanges();
                TempData["success"] = "Variant created successfully";
                return RedirectToAction("Index","Product");
            return View(variant);
        }
    }
}

Web/Views/Product/CreateVariant.cshtml
@model TotalProduct;
@{
	Layout = "_LayoutAdmin";

	List<Color> colors= this.ViewBag.Colors;
	List<Size> sizes = this.ViewBag.Sizes;
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

<form method="post" asp-controller="Product" asp-action="CreateVariant" asp-route-productId="@Model.product.id">
	
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create Variant for</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		@*<input asp-for="product.id" value="@Model.product.id" hidden />*@

		@*id varianty:<input asp-for="id" value="@Model.id"/>*@
		@*@Model.id*@

		<div class="mb-3 col-6">
					<label asp-for="color_id"></label>
					<select asp-for="color_id" class="form-select">
						@foreach (Color color in colors)
						{
							<option value="@color.id">@color.color</option>
						}

					</select>
		</div>
		<div class="mb-3 col-6">
			<label asp-for="size_id"></label>
			<select asp-for="size_id" class="form-select">
				@foreach (Size size in sizes)
				{
					<option value="@size.id">@size.size</option>
				}

			</select>
		</div>
		@*<div class="mb-3">
			<label asp-for=""></label>
			<input asp-for="DisplayOrder" class="form-control" />
			<span asp-validation-for="DisplayOrder" class="text-danger"></span>
		</div>*@
		<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
		<a asp-controller="Product" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to Variant List
		</a>
		@*asp-route-id="@Model.product_id"*@
	</div>
</form>

Web/Views/Product/DelVariant.cshtml
@{
	@model TotalProduct;
	Layout = "_LayoutAdmin";
	List<Product> products=this.ViewBag.Products;
	List<Color> colors = this.ViewBag.Colors;
	List<Size> sizes = this.ViewBag.Sizes;
	Product selectedProduct = products.Where(c => c.id == Model.product.id).FirstOrDefault();
	Color selectedColor = colors.Where(c => c.id == Model.color_id).FirstOrDefault();
	Size selectedSize = sizes.Where(c => c.id == Model.size_id).FirstOrDefault();
}

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
<form method="post" asp-action="DelVariant" enctype="multipart/form-data">
	<input asp-for="id" hidden />

	<div class="row">
		<div class="col-2">
			<div class="border p-3 mt-4 row">
				<div class="col-12 pb-2">
					<h2 class="text-primary">Delete variant</h2>
					<hr />
				</div>
				<div class="mb-3">
					<label asp-for="product.id">Produkt</label>
					<input asp-for="product.id" class="form-control" hidden/>
					<input value="@selectedProduct.name" class="form-control" disabled/>
					<span asp-validation-for="product.id" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="color_id">Barva</label>
					<input asp-for="color_id" class="form-control" hidden/>
					<input value="@selectedColor.color" class="form-control" disabled/>
					<span asp-validation-for="color_id" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="size_id">Velikost</label>
					<input asp-for="size_id" class="form-control" hidden/>
					<input value="@selectedSize.size" class="form-control" disabled/>
					<span asp-validation-for="size_id" class="text-danger"></span>
				</div>

				<div class="col-12">
					<button type="submit" class="btn btn-primary" style="width:150px">Delete</button>
					<a asp-controller="Product" asp-route-id="@Model.product.id" asp-action="Variant" class="btn btn-secondary" style="width:150px">
						Back to List
					</a>
				</div>
			</div>
		</div>

	</div>







</form>

Web/Views/Product/Delete.cshtml
@model Product;
@{
    Layout = "_LayoutAdmin"; 

	MyContext context = new MyContext();
	List<Category> categories = context.Categories.ToList();
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

<form method="post" asp-action="Delete" enctype="multipart/form-data">
	<input asp-for="id" hidden />

	<div class="row">
		<div class="col-10">
			<div class="border p-3 mt-4 row">
				<div class="col-12 pb-2">
					<h2 class="text-primary">Delete product</h2>
					<hr />
				</div>
				<div class="mb-3">
					<label asp-for="name"></label>
					<input asp-for="name" class="form-control" disabled/>
				</div>
				<div class="mb-3">
					<label asp-for="desc"></label>
					<textarea asp-for="desc" rows="3" class="form-control" disabled></textarea>
				</div>
				<div class="mb-3 col-6">
					<label asp-for="SKU"></label>
					<input asp-for="SKU" class="form-control" disabled />
				</div>
				<div class="mb-3 col-6">
					<label asp-for="price"></label>
					<input asp-for="price" class="form-control" disabled />
				</div>

				<div class="mb-3 col-6">
					<label asp-for="category_id"></label>
					<select disabled asp-for="category_id" class="form-select">
						@foreach (Category cat in categories)
						{
							<option value="@cat.id">@cat.name</option>
						}

					</select>
				</div>

				<div class="col-12">
					<button type="submit" class="btn btn-primary" style="width:150px">Delete</button>
					<a asp-controller="Product" asp-action="Index" class="btn btn-secondary" style="width:150px">
						Back to List
					</a>
				</div>
			</div>
		</div>

	</div>







</form>

Web/Views/Product/Index.cshtml
@model List<Product>;
@{
    Layout = "_LayoutAdmin";
    MyContext context = new MyContext();
    List<Category> categories = context.Categories.ToList();
    List<Image> Images = this.ViewBag.Images;
    <h2>@TempData["success"]</h2>
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
<link rel="stylesheet" href="~/lib/lightbox2/css/lightbox.css" />

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Product List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Product" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Product
            </a>
            <a asp-controller="Home" asp-action="Index" class="btn btn-secondary">
                <i class="bi bi-plus-circle"></i> &nbsp; Back to site
            </a>
        </div>
    </div>
    <br /><br />

    <table id="tblData" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Název</th>
                <th>Popis</th>
                <th>SKU</th>
                <th>cena</th>
                <th>Kategorie</th>
                <th>Hl.obraz</th>
                <th>Akce</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>
                        @obj.name
                    </td>
                    <td>
                        @obj.desc
                    </td>
                    <td>
                        @obj.SKU
                    </td>
                    <td>
                        @obj.price
                    </td>
                    <td>
                        @{
                            Category selected = categories.Where(c => c.id == obj.category_id).FirstOrDefault();

                            if (selected != null)
                            {
                                                @selected.name;
                            }
                            
                            }
                            </td>
                            <td>
                                
                                @*<img src="@obj.photoMain" width="100px" style="border-radius:5px; border:1px solid #bbb9b9" />*@

                        <a class="example-image-link" href="@{
                                foreach (Image item in Images)
                            {
                                if (item.product_id == obj.id && item.priority == 1)
                                {
                                                        @item.path;
                          }
                         }
    }" data-lightbox="example-1">
                            <img width="100px" src="@{
                            foreach (Image item in Images)
                            {
                                if (item.product_id == obj.id && item.priority == 1)
                                {
                                        @item.path;
                                }
                         }}" /></a>
                                @*@{
                            foreach(Image img in Images){
                                if (obj.id==img.product_id)
                                {
                                    //<img  src="@img.path" width="100px" style="border-radius:5px; border:1px solid #bbb9b9" />
                                    <a class="example-image-link" href="@img.path" data-lightbox="example-1"><img width="100px" src="@img.path" /></a>

                                }
                            }
                        }*@
                            </td>
                    
                            <td>
                                <div class="w-75 btn-group" role="group">
                                    <a asp-controller="Product" asp-action="Upsert" asp-route-id="@obj.id"
                           class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                                    <a asp-controller="Product" asp-action="Delete" asp-route-id="@obj.id"
                           class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                                    <a asp-controller="Product" asp-action="Variant" asp-route-id="@obj.id"
                           class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i>Spravovat Var</a>
                                </div>
                            </td>
                        </tr>
            }
        </tbody>
    </table>
</div>
<script src="~/lib/js/lightbox.js"></script>
@*<script src="~/lib/js/lightbox-plus-jquery.min.js"></script>*@

Web/Views/Product/Upsert.cshtml
@model Product;
@{
    Layout = "_LayoutAdmin"; 

	MyContext context = new MyContext();
	List<Category> categories = context.Categories.ToList();
	List<Image> Images=context.Images.ToList();
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

<form method="post" asp-action="Upsert" enctype="multipart/form-data">
	<input asp-for="id" hidden />
	@*<input asp-for="photoMain" hidden />*@

	<div class="row">
		<div class="col-10">
			<div class="border p-3 mt-4 row">
				<div class="col-12 pb-2">
					<h2 class="text-primary">@(Model.id != 0 ? "Update" : "Create")  Product</h2>
					<hr />
				</div>
				<div asp-validation-summary="All"></div>
				<div class="mb-3">
					<label asp-for="name"></label>
					<input asp-for="name" class="form-control" />
					<span asp-validation-for="name" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="desc"></label>
					<textarea asp-for="desc" rows="3" class="form-control"></textarea>
					<span asp-validation-for="desc" class="text-danger"></span>
				</div>
				<div class="mb-3 col-6">
					<label asp-for="SKU"></label>
					<input asp-for="SKU" class="form-control" />
					<span asp-validation-for="SKU" class="text-danger"></span>
				</div>
				<div class="mb-3 col-6">
					<label asp-for="price"></label>
					<input asp-for="price" class="form-control" />
					<span asp-validation-for="price" class="text-danger"></span>
				</div>
				@*<div class="mb-3 col-6">
				<label asp-for="photoMain"></label>
				<input asp-for="photoMain" class="form-control" />
				<span asp-validation-for="photoMain" class="text-danger"></span>
				</div>*@
				<div class="mb-3">
					<label >Hlavní obrázek</label>
					<input  type="file" name="mainPhoto" class="form-control" />
				</div>
				<div class="mb-3">
					<label>Doplňující obrázky</label>
					<input  type="file" name="listImages" class="form-control" multiple/>
				</div>

				<div class="mb-3 col-6">
					<label asp-for="category_id"></label>
					<select asp-for="category_id" class="form-select">
						@foreach (Category cat in categories)
						{
							<option value="@cat.id">@cat.name</option>
						}

					</select>
					<span asp-validation-for="category_id" class="text-danger"></span>
				</div>

				<div class="col-12">
					@*@if (Model.Product.id != 0)
					{
					<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
					}
					else
					{
					<button type="submit" onclick="return ValidateInput()" class="btn btn-primary" style="width:150px">Create</button>
					}*@
					<button type="submit" onclick="return ValidateInput()" class="btn btn-primary" style="width:150px">@(Model.id != 0 ? "Update" : "Create")</button>
					<a asp-controller="Product" asp-action="Index" class="btn btn-secondary" style="width:150px">
						Back to List
					</a>
				</div>
				@*@if (Model.photoMain!=null)
				{
				<div class="col-2 pt-4">
				<img src="@Model.photoMain"
				width="100%" style="border-radius:5px; border:1px solid #bbb9b9" />
				</div>
				}*@
			</div>
		</div>

	</div>
	@if (Model.id!=null)
	{
		<div class="d-flex gap-4 ">
			<table class="table table-bordered table-striped w-25" >
				<thead>
					<tr>
						<th>
							Doplňující obrázky
						</th>
						<th>
							Akce
						</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Images)
					{
						if (item.product_id == Model.id && item.priority == 2)
						{
							<tr style="height:50px">
								<td class="w-25">
									<img width="100px" src="@item.path" />
								</td>
								<td>
									<div class=" btn-group" role="group">
										@*<a asp-controller="Images" asp-action="Edit" asp-route-id="@item.id"
							class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i>Edit</a>*@
										<a asp-controller="Image" asp-action="Delete" asp-route-id="@item.id" asp-route-productID="@Model.id"
							   class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
										@*@this.TempData["backtosite"]=@Model.id;*@
									</div>
								</td>
							</tr>

						}
					}
				</tbody>

			</table>
			<table class="table table-bordered table-striped" style="width:35%;height:100px">
				<thead>
					<tr>
						<th>
							Hlavní obrázek
						</th>
						<th>
							Akce
						</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Images)
					{
						if (item.product_id == Model.id && item.priority == 1)
						{
							<tr>
								<td >
									<img style="height:100px" src="@item.path" />
								</td>
								<td>
									<div class="w-75 btn-group" role="group">
										<a asp-controller="Image" asp-action="Delete" asp-route-id="@item.id"
							   class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
										@*@{this.ViewBag.BackToSite=@Model.id}*@
									</div>
								</td>
							</tr>

						}
					}
				</tbody>

			</table>
		</div>
	}	



</form>

Web/Views/Product/Variant.cshtml
@model Product;
@{
    MyContext context = new MyContext();
    Layout = "_LayoutAdmin"; 
    List<TotalProduct> variants = context.Variants.ToList();
    List<Product> products = context.Products.ToList();
    List<Color> colors= context.Colors.ToList();
    List<Size> sizes= context.Sizes.ToList();
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Variant List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Product" asp-action="CreateVariant" asp-route-id="@Model.id" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Variant
            </a>
            <a asp-controller="Home" asp-action="Index" class="btn btn-secondary">
                <i class="bi bi-plus-circle"></i> &nbsp; Back to site
            </a>
            <a asp-controller="Product" asp-action="Index" class="btn">
                <i class="bi bi-plus-circle"></i> &nbsp; Back to Variants
            </a>
        </div>
    </div>
    <br /><br />
    <h2 class="h2">@Model.name</h2>
    <table id="tblData" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Barva</th>
                <th>Velikost</th>
            </tr>
        </thead>
        <tbody>
           
            @foreach (var item in context.Variants)
            {
                if (Model.id == item.product.id)
                {
                    <tr>
                        <td>
                            @{
                                Color color = context.Colors.Find(item.color_id);
                                @color.color;
                            }
                        </td>
                        <td>
                            @{
                                Size size = context.Sizes.Find(item.size_id);
                                @size.size;
                            }
                        </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Product" asp-action="DelVariant" asp-route-id="@item.id"
                   class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                    </div>
                </td>
                    </tr>
                }
            }  
            
        </tbody>
    </table>
</div>